# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '01_00_菜单栏划入' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 01_00_菜单栏划入
  pod 'YYKit', '~> 1.0.9'

  target '01_00_菜单栏划入Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '01_00_菜单栏划入UITests' do
    # Pods for testing
  end

end
