# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '01_SlideMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 01_SlideMenu
  pod 'YYKit', '~> 1.0.9'

  target '01_SlideMenuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '01_SlideMenuUITests' do
    # Pods for testing
  end

end
